config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get 'static/home'
  get 'static/about'

  root to: "static#home"

  get "profile", to: "users/profile#show"

  get 'motorcycles/search', as: 'motorcycles_search'

  resources :motorcycles do
    resources :bookings, only: [:new, :create]
     resources :photos, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :motorcycle
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :motorcycle
  validates_presence_of :user_id, :motorcycle_id, :pickup_date, :return_date
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :booking
  belongs_to :user
end

app/models/motorcycle.rb
class Motorcycle < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :photos

  geocoded_by :full_address
  after_validation :geocode

  MANUFACTURERS = %w(BMW Ducati Guzzi Honda Kawasaki Suzuki Triumph Yamaha)
  STYLES = %w(Roadster Trail Supermotard Trial Custom Sport)

  validates_presence_of :manufacturer ,:model, :production_year, :engine_size, :engine_type, :horsepower, :license_plate, :pickup_address, :style, :city, :zip_code, :price_per_day

  private

  def full_address
    "#{self.pickup_address}, #{self.zip_code}, #{self.city}"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :motorcycle

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email

  devise :omniauthable, :omniauth_providers => [ :facebook ]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver
  end

end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.total_price = (booking_params[:return_date].to_f - booking_params[:pickup_date].to_f) * @booking.motorcycle.price_per_day
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def get_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:motorcycle_id, :pickup_date, :return_date)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # def destroy
  #   @comment = Comment.find(params[:id])
  #   @comment.destroy if @comment.owner == current_user
  # end

end

app/controllers/motorcycle_controller.rb
class MotorcycleController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :get_motorcycle, only: [:create, :new]

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.motorcycle = @motorcycle
    if @photo.save
      redirect_to motorcycle_path(@motorcycle)
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :motorcycle_id)
  end

  def get_motorcycle
    @motorcycle = Motorcycle.find(params[:motorcycle_id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authenticate_user!

  def home

  end

  def about

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/motorcycle_helper.rb
module MotorcycleHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_sessions.html.erb
<% if user_signed_in? %>
  <%= current_user.email %>
  <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Drive me free! | Rent a motorcycle" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>

    <%= render "shared/navbar" %>

    <%= render 'shared/notices' %>

    <%= yield %>
    <%= render "shared/footer" %>


    <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:js) %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-center">
  <a href="twitter.com"><i class="fa fa-twitter fa-2x"></i></a>
  <a href="facebook.com"><i class="fa fa-facebook fa-2x"></i></a>
  <a href="instagram.com"><i class="fa fa-instagram fa-2x"></i></a>
  <a href="youtube.com"><i class="fa fa-youtube fa-2x"></i></a>
  <p>driveforfree.cz</p>
</footer>

app/views/shared/_modal_signup.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up</h4>
      </div>
      <div class="modal-body">

        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :first_name, as: :string, required: true, autofocus: true %>
            <%= f.input :last_name, as: :string, required: true %>
            <%= f.input :birthday, as: :date, required: true %>
            <%= f.input :email, required: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable) %>
            <%= f.input :password_confirmation, required: true %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png", id: "logo" %>
      </a>
    </div>
    <%= render user_signed_in? ? 'shared/navbar_loggued_in' : 'shared/navbar_loggued_out' %>
  </div>
</nav>

app/views/shared/_navbar_loggued_in.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
        <% if current_user.provider %>
            <%= image_tag current_user.picture, class: "img img-circle" %>
        <% end %>
        <%= current_user.email %>
        <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "/profile" do %>
          <i class="fa fa-user"></i> Profile
          <% end %>
        </li>
        <li>
          <%= link_to motorcycles_path do %>
            <i class="fa fa-home"></i> Motorcycles
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i> Sign Out
          <% end %>
        </li>
      </ul>
    </li>
    <li>
      <%= link_to "#" do %>
      <i class="fa fa-envelope-o"></i>
      <% end %>
    </li>
    <li>
      <%= link_to new_motorcycle_path, class: "btn btn-primary", id: "nav-btn" do %>
        List Your Motorcycle
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_navbar_loggued_out.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
    </li>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
    <li>
      <%= link_to motorcycles_path, class: "btn btn-primary", id: "nav-btn" do %>
        List Your Motorcycle
      <% end %>
    </li>
  </ul>
</div><!-- /.navbar-collapse -->

app/views/shared/_notices.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <!-- Devise alerts -->
    <%= alert %>
  </div>
<% end %>