config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get 'static/home'
  get 'static/about'

  root to: "static#home"

  get "profile", to: "users/profile#show"

  get 'motorcycles/search', as: 'motorcycles_search'

  resources :motorcycles do
    resources :bookings, only: [:new, :create]
     resources :photos, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/motorcycle.rb
class Motorcycle < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :photos

  geocoded_by :full_address
  after_validation :geocode

  MANUFACTURERS = %w(BMW Ducati Guzzi Honda Kawasaki Suzuki Triumph Yamaha)
  STYLES = %w(Roadster Trail Supermotard Trial Custom Sport)

  validates_presence_of :manufacturer ,:model, :production_year, :engine_size, :engine_type, :horsepower, :license_plate, :pickup_address, :style, :city, :zip_code, :price_per_day

  private

  def full_address
    "#{self.pickup_address}, #{self.zip_code}, #{self.city}"
  end

end

app/controllers/motorcycle_controller.rb
class MotorcycleController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :get_motorcycle, only: [:show, :edit, :update, :destroy]

  def index

    @motorcycles = Motorcycle.all

    @markers = Gmaps4rails.build_markers(@motorcycles) do |motorcycle, marker|
      marker.lat motorcycle.latitude
      marker.lng motorcycle.longitude
    end
  end

  def show
    @alert_message = "Check that #{@motorcycle.model} !"
    @motorcycle_coordinates = { lat: @motorcycle.latitude, lng: @motorcycle.longitude }
    @booking = Booking.new(pickup_date: session[:search_params]["start_date"],
      return_date: session[:search_params]["end_date"])
  end

  def new
    @motorcycle = Motorcycle.new
  end

  def create
    @motorcycle = Motorcycle.new(motorcycle_params)
    if @motorcycle.save
      redirect_to motorcycle_path(@motorcycle)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @motorcycle.update(motorcycle_params)

    redirect_to motorcycle_path(@motorcycle)
  end

  def destroy
    @motorcycle.destroy

    redirect_to motorcycles_path
  end

  def search
    @motorcycles = Motorcycle.where(search_params.reject{|_, v| v.blank?})
    search_params = {start_date: params[:start_date], end_date: params[:end_date]}
    session[:search_params] = search_params

    @markers = Gmaps4rails.build_markers(@motorcycles) do |motorcycle, marker|
      marker.lat motorcycle.latitude
      marker.lng motorcycle.longitude
    end
  end



  private

  def get_motorcycle
    @motorcycle = Motorcycle.find(params[:id])
  end

  def motorcycle_params
    params.require(:motorcycle).permit(:manufacturer, :model, :style, :production_year, :engine_size, :engine_type, :horsepower, :license_plate, :description, :pickup_address, :longitude, :latitude, :autonomy_km, :picture, :price_per_day, :zip_code, :city)
  end

  def search_params
    params.permit(:manufacturer, :model, :style, :production_year, :engine_size, :engine_type, :horsepower, :license_plate, :description, :pickup_address, :longitude, :latitude, :autonomy_km, :picture, :city)
  end
end

app/helpers/motorcycle_helper.rb
module MotorcycleHelper
end

app/views/motorcycles/_carousel.html.erb
<% @motorcycle.photos.each do |photo| %>
  <%= image_tag photo.picture.url(:medium) %>
<% end %>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
      <% i == 1 %>
    <% @motorcycle.photos.each do |photo| %>
      <li data-target="#carousel-example-generic" data-slide-to= <%= i %> ></li>
      <% i += 1 %>
    <% end %>
  </ol>
<!--   <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/motorcycles/_form.html.erb
<%= simple_form_for @motorcycle , html: {class: "horizontal-form"} do |f| %>

  <%= f.input :manufacturer, collection: Motorcycle::MANUFACTURERS %>
  <%= f.input :model %>
  <%= f.input :style, collection: Motorcycle::STYLES %>
  <%= f.input :production_year %>
  <%= f.input :engine_size %>
  <%= f.input :engine_type %>
  <%= f.input :horsepower %>
  <%= f.input :license_plate %>
  <%= f.input :description %>
  <%= f.input :pickup_address %>
  <%= f.input :city %>
  <%= f.input :zip_code %>
  <%= f.input :autonomy_km %>
  <%= f.input :price_per_day %>

  <div class="form-actions text-center">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

<!-- Include Google Maps JS API -->
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?libraries=places&key=PUT_YOUR_OWN_KEY_HERE">
</script>

<!-- Custom JS code to bind to Autocomplete API -->
<!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
<!-- We'll detail this file in the article -->
<script type="text/javascript" src="autocomplete.js"></script>

app/views/motorcycles/_search.html.erb
<div class="row">
  <div class="col-xs-12">
    <form action="<%= motorcycles_search_path %>" class="form-horizontal">
      <div class="form-group">
        <label for="manufacturer" class="col-sm-2 control-label">Manufacturer</label>
        <div class="col-sm-9">
          <input type="text" name="manufacturer" id="manufacturer" class="form-control" placeholder="BMW">
        </div>
      </div>
      <div class="form-group">
        <label for="model" class="col-sm-2 control-label">Model</label>
          <div class="col-sm-9">
            <input type="text" name="model" id="model" class="form-control" placeholder="R1200GS">
          </div>
      </div>
      <div class="form-group">
        <label for="style" class="col-sm-2 control-label">Style</label>
          <div class="col-sm-9">
            <input type="text" name="style" id="style" class="form-control" placeholder="Supermotard">
          </div>
      </div>
      <div class="form-group">
        <label for="engine_size" class="col-sm-2 control-label">Engine size</label>
          <div class="col-sm-9">
            <input type="text" name="engine_size" id="engine_size" class="form-control" placeholder="1200">
          </div>
      </div>
      <input type="submit" value="Filter" class="btn btn-primary col-sm-offset-2">
    </form>
  </div>
</div>


<script>
$(function() {
  var availableTags = <%= raw(Motorcycle::MANUFACTURERS.to_json) %>;
  $( "#manufacturer" ).autocomplete({
    source: availableTags
  });
});
</script>

<script>
$(function() {
  var availableTags = <%= raw(Motorcycle::STYLES.to_json) %>;
  $( "#style" ).autocomplete({
    source: availableTags
  });
});
</script>

app/views/motorcycles/_vignettes.html.erb
<div class="row">
  <% @motorcycles.each do |motorcycle| %>
    <div class="col-xs-12 col-sm-6">
      <div class="vignette">
        <% unless motorcycle.photos.empty? %>
          <%= image_tag motorcycle.photos.first.picture.url(:medium), class:'img-responsive' %>
        <% end %>
        </br>
        <%= link_to (motorcycle.manufacturer + " - " + motorcycle.model + " from " + motorcycle.production_year.to_s), motorcycle_path(motorcycle) %></br>
        <%= motorcycle.style + " of " + motorcycle.engine_size.to_s  + " cm3 - " + motorcycle.pickup_address %>
      </div>
    </div>
  <% end %>
</div>

app/views/motorcycles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="center-form">

        <h2>Modifier votre <%= @motorcycle.manufacturer %>, <%= @motorcycle.model %></h2>

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/motorcycles/index.html.erb
<div class="search">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-md-8">
        <%= render 'search' %>
        <%= render 'vignettes' %>
      </div>

      <div class="col-xs-12 col-md-4">
       <div id="map" style="width: 100%; height: 1000px;"></div>
     </div>

    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/motorcycles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="center-form">

        <h2>New Motorcycle</h2>

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/motorcycles/search.html.erb
<div class="search">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-md-8">
        <%= render 'search' %>
        <%= render 'vignettes' %>
      </div>

      <div class="col-xs-12 col-md-4">
       <div id="map" style="width: 100%; height: 1000px;"></div>
     </div>

    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/motorcycles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">

      <div class="center-form" style="border: 0px solid black">

        <h2><%= @motorcycle.manufacturer %>, <%= @motorcycle.model %></h2>

        <div class="show-div show-photos">
          <% @motorcycle.photos.each do |photo| %>
            <%= image_tag photo.picture.url(:medium) %>
          <% end %>
          <%#= render 'carousel' %>
        </div>

        <div class="text-center">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-5">
              <div class="row text-center">
                <div class="col-xs-6">
                  photo</br> first_name
                </div>
                <div class="col-xs-6">
                  <%= @motorcycle.manufacturer %>, <%= @motorcycle.model %></br>
                  <%= @motorcycle.city %>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-1">
            </div>

            <div class="col-xs-12 col-sm-12 col-md-6 border-darkgrey offset-left-20px">
              <div class="row booking-title">
                <div class="col-xs-12 col-sm-12">
                  <%= @motorcycle.price_per_day %>€ / day
                </div>
              </div>
              <div class="row booking-content">
                </br>
                <%= simple_form_for [@booking], url: motorcycle_bookings_path(@motorcycle) do |f| %>
                  <%= f.hidden_field :motorcycle_id, value: @motorcycle.id %>
                  <div class="col-xs-12 col-sm-12">
                    <div class="row booking-fields">
                      <div class="col-xs-6 col-sm-6">
                        <%= f.input :pickup_date, as: :string, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year], placeholder:'dd/mm/yyyy', input_html: { class: 'datepicker' }, required: true %>
                      </div>
                      <div class="col-xs-6 col-sm-6">
                        <%= f.input :return_date, as: :string, start_year: Time.now.year - 90, end_year: Time.now.year - 8, order: [:day, :month, :year], placeholder:'dd/mm/yyyy', input_html: { class: 'datepicker' }, required: true %>
                      </div>
                    </div>
                    <div class="row booking-send">
                      <div class="col-xs-12 col-sm-12">
                        <%= f.button :submit, 'Book now!', id: "nav-btn" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>

            </div>
          </div>
        </div>

        <div class="show-div show-caracteristics">
          <div class="text-center">
            <h3>Motorcycle on the map !</h3>
          </div>
          <div id="map" style='width: 100%; height: 134px;'></div>
        </div>


        <div class="show-div show-caracteristics">
          <div class="text-center">
            <h3>Characteristics</h3>
          </div>
          <div class="row text-center margin-bottom-10">
            <div class="col-xs-12 col-sm-6 col-md-3">
              Manufacturer: <strong><%= @motorcycle.manufacturer %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Model: <strong><%= @motorcycle.model %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Style: <strong><%= @motorcycle.style %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Production year: <strong><%= @motorcycle.production_year %></strong>
            </div>
          </div>
          <div class="row text-center">
            <div class="col-xs-12 col-sm-6 col-md-3">
              Engine size: <strong><%= @motorcycle.engine_size %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Engine type: <strong><%= @motorcycle.engine_type %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Horsepower: <strong><%= @motorcycle.horsepower %></strong>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              Autonomy (km): <strong><%= @motorcycle.autonomy_km %></strong>
            </div>
          </div>
        </div>

        <div class="show-div show-description">
          <div class="text-center">
            <h3>Description</h3>
          </div>
          <div class="row">
            <div class="col-xs-12">
              Description: <%= @motorcycle.description %>
            </div>
          </div>
        </div>

        <div class="show-actions">
          <div class="row">
            <div class="col-xs-12">
              <%= link_to 'Add photo', new_motorcycle_photo_path(@motorcycle) %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <%= link_to 'Edit', edit_motorcycle_path %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <%= link_to "Delete", @motorcycle, method: :delete %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <%= link_to 'Back', motorcycles_path  %>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

  <script src="https://wagon-google-maps-markers.herokuapp.com/assets/application-5034196864c74ae1cc5f12e6d1f71223.js" type="text/javascript"></script>

  <script type="text/javascript">
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers([
            { "lat": <%= raw @motorcycle.latitude %>, "lng": <%= raw @motorcycle.longitude %> },
          ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  </script>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('.datepicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true
      });
    });
  <% end %>
<% end %>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @motorcycle_coordinates %>;
      alert('Motorcycle coordinates are ' + coord.lat + ', ' + coord.lng);
    });
  <% end %>
<% end %>